#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "curl -sf http://localhost:80/" \
        s6-setuidgid abc darkhttpd /app/ariang --port 80
else
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "curl -sf http://localhost:80/" \
        darkhttpd /app/ariang --port 80
fi