#!/usr/bin/with-contenv bash
# shellcheck shell=bash

RPC_PORT=$(grep -Po "^rpc-listen-port=\K(.*)" /config/aria2.conf)

check_aria2_health() {
    local response
    response=$(curl -s -X POST "http://localhost:${RPC_PORT:-6800}/jsonrpc" \
        -H "Content-Type: application/json" \
        -d '{"jsonrpc":"2.0","method":"aria2.getVersion","id":"healthcheck","params":[]}' \
        2>/dev/null)
    
    if echo "${response}" | grep -q '"result"'; then
        return 0
    else
        return 1
    fi
}

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "check_aria2_health" \
        s6-setuidgid abc aria2c --conf-path=/config/aria2.conf
else
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "check_aria2_health" \
        aria2c --conf-path=/config/aria2.conf
fi