#!/usr/bin/with-contenv bash
# shellcheck shell=bash

if [[ -z ${LSIO_NON_ROOT_USER} ]]; then
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "/usr/local/bin/check_aria2_health" \
        s6-setuidgid abc aria2c --conf-path=/config/aria2.conf
else
exec \
    s6-notifyoncheck -d -n 300 -w 1000 -c "/usr/local/bin/check_aria2_health" \
        aria2c --conf-path=/config/aria2.conf
fi